// SPDX-FileCopyrightText: 2025 David Andrs <andrsd@gmail.com>
// SPDX-License-Identifier: MIT

#pragma once

#include "krado/types.h"
#include "krado/ptr.h"
#include <vector>
#include <array>
#include <iostream>

namespace krado {

class MeshVertexAbstract;
class Point;

/// Mesh element (generated by a mesh generator, i.e. not read from a mesh file)
class MeshElement {
public:
    /// Build an element
    ///
    /// @param type Element type
    /// @param vtx Vertices composing the element
    MeshElement(ElementType type, const std::vector<Ptr<MeshVertexAbstract>> & vtx);
    ~MeshElement();

    /// Get element type
    ///
    /// @return Element type
    [[nodiscard]] ElementType type() const;

    /// Get number of vertices
    ///
    /// @return Number of vertices
    [[nodiscard]] int num_vertices() const;

    /// Get vertex from local index
    ///
    /// @param idx Local vertex index
    /// @return Vertex
    [[nodiscard]] Ptr<MeshVertexAbstract> vertex(int idx) const;

    Span<const Ptr<MeshVertexAbstract>> vertices() const;

    MeshElement get_edge(int i) const;

    /// Swap two vertices
    ///
    /// @param idx1 Index of the first vertex
    /// @param idx2 Index of the second vertex
    ///
    /// @note This is useful for reorienting elements
    void swap_vertices(int idx1, int idx2);

private:
    ElementType type_;
    std::vector<Ptr<MeshVertexAbstract>> vtx_;

public:
    static MeshElement Line2(const std::array<Ptr<MeshVertexAbstract>, 2> & vtx);
    static MeshElement Tri3(const std::array<Ptr<MeshVertexAbstract>, 3> & vtx);
    static MeshElement Quad4(const std::array<Ptr<MeshVertexAbstract>, 4> & vtx);
};

std::vector<int> sorted_vertex_nums(const MeshElement & elem);

/// Compute circum radius using quality norm
double circum_radius_quality(const MeshElement & tri);

/// Compute circum radius using euclidina norm
double circum_radius_euclidian(const MeshElement & tri, double lc);

/// Compute barycenter
///
/// @param elem Mesh element
/// @return Barycenter
Point barycenter(const MeshElement & elem);

} // namespace krado

std::ostream & operator<<(std::ostream & stream, const krado::MeshElement & el);
